version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meridi-api
    restart: unless-stopped
    volumes:
      # This is the new volume mounting for your web service
      # It mounts the 'fastapi_data' named volume to /app/data inside the container.
      # You can change '/app/data' to any path where your app needs to write persistent data.
      - fastapi_data:/app/data/
      # If you have logs you want to persist outside the container:
      # - fastapi_logs:/app/logs
    env_file:
      - .env # Optional: For environment variables
    ports:
      - "8081:8000" # Expose app internally on port 8000 for Nginx to connect
    depends_on:
      -  db
      # - nginx # Ensure Nginx starts after the web service

  # nginx:
  #   image: nginx:stable-alpine # Use a lightweight Nginx image
  #   container_name: nginx-proxy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"   # Expose port 80 for HTTP traffic
  #     - "443:443" # Expose port 443 for HTTPS traffic (if you configure it)
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Custom Nginx config
  #     - ./nginx/conf.d:/etc/nginx/conf.d:ro        # Custom server blocks
  #     # If you plan to use Certbot for SSL, you'll need volumes for certificates:
  #     # - ./certbot/www:/var/www/certbot:ro # For Certbot webroot authentication
  #     # - ./certbot/conf:/etc/nginx/conf.d:ro # For Certbot managed Nginx config (optional)
  #     # - ./certbot/data:/etc/letsencrypt # For Let's Encrypt certificates (optional)
  #   depends_on:
  #     - web # Nginx depends on the web service being available
   db:
    image: postgres:14-alpine # Use a stable and lightweight PostgreSQL image
    container_name: postgres-db
    restart: unless-stopped
    env_file:
      - .env_db # NEW: Separate .env file for database credentials (recommended)
    volumes:
      - pgdata:/var/lib/postgresql/data # Persistent volume for PostgreSQL data
    ports:
      - "5432:5432" # Optional: Expose PostgreSQL port to host for local access/debugging
                  # Remove this line in production if you only want internal container access
volumes:
  # Optional: For persistent data if your app ever needs it
  fastapi_data:
  #   driver: local